// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQFbftLEIYseR3inHeDiaxi8qkTYBH8TQ',
    appId: '1:282771332137:web:e0465308ce66e7d9d51038',
    messagingSenderId: '282771332137',
    projectId: 'bustracklk',
    authDomain: 'bustracklk.firebaseapp.com',
    storageBucket: 'bustracklk.firebasestorage.app',
    measurementId: 'G-BF6MZWDLX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpJr_ftEzQTcSLTgbijOEq9AasM7D8FBk',
    appId: '1:282771332137:android:2ad16e7fabc94f41d51038',
    messagingSenderId: '282771332137',
    projectId: 'bustracklk',
    storageBucket: 'bustracklk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBUWKlRGqAibWSu3QbdqiAncFJQchyJx0',
    appId: '1:282771332137:ios:86d55b37a0715712d51038',
    messagingSenderId: '282771332137',
    projectId: 'bustracklk',
    storageBucket: 'bustracklk.firebasestorage.app',
    iosBundleId: 'com.example.driverUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBUWKlRGqAibWSu3QbdqiAncFJQchyJx0',
    appId: '1:282771332137:ios:86d55b37a0715712d51038',
    messagingSenderId: '282771332137',
    projectId: 'bustracklk',
    storageBucket: 'bustracklk.firebasestorage.app',
    iosBundleId: 'com.example.driverUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQFbftLEIYseR3inHeDiaxi8qkTYBH8TQ',
    appId: '1:282771332137:web:804623fef2318362d51038',
    messagingSenderId: '282771332137',
    projectId: 'bustracklk',
    authDomain: 'bustracklk.firebaseapp.com',
    storageBucket: 'bustracklk.firebasestorage.app',
    measurementId: 'G-PRX24Y4F1Y',
  );
}
