name: finalproject
description: A Flutter bus tracking application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0              # For API calls
  provider: ^6.1.5+1          # State management
  shared_preferences: ^2.5.3 # Local storage
  intl: ^0.20.2             # Date formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
