class AppLocalizations {
  static Map<String, Map<String, String>> translations = {
    'English': {
      'app_name': 'BusTrackLK',
      'driver_name': 'Driver Name',
      'start_location': 'Start Location',
      'end_location': 'End Location',
      'start_journey': 'Start Journey',
      'profile': 'Profile',
      'about': 'About',
      'your_account_details': 'Your account details',
      'learn_more_about_us': 'Learn more about us',
      'copyright': '© 2025 BusTrackLK App. All Rights Reserved.',
      'user_name': 'User Name',
      'phone_no': 'Phone No',
      'email': 'Email',
      'password': 'Password',
      'bus_no': 'Bus No',
      'route_no': 'Route No',
      'register': 'Register',
      'login': 'Login',
      'forgot_password': 'Forgot Password?',
      'registration_success': 'Registration Success',
      'ok': 'OK',
      'logout': 'Logout',
      'about_us': 'About Us',
      'version': 'Version',
      'developed_by': 'Developed by',
      'released_date': 'Released Date',
      'about_description':
          'Tired of the endless waiting and uncertainty of bus travel? We are too.\n\nAs daily commuters and software engineering students, we\'re building BusTrackLK. Our mission is to put real time bus tracking and schedules to easy seat booking, making travel more simple and predictable for our entire community.',
    },
    'Sinhala': {
      'app_name': 'බස්ට්‍රැක්LK',
      'driver_name': 'රියදුරු නම',
      'start_location': 'ආරම්භක ස්ථානය',
      'end_location': 'අවසාන ස්ථානය',
      'start_journey': 'ගමන ආරම්භ කරන්න',
      'profile': 'පැතිකඩ',
      'about': 'පිළිබඳව',
      'your_account_details': 'ඔබේ ගිණුම් විස්තර',
      'learn_more_about_us': 'අප ගැන වැඩිදුර දැනගන්න',
      'copyright': '© 2025 බස්ට්‍රැක්LK යෙදුම. සියලුම හිමිකම් ඇවිරිණි.',
      'user_name': 'පරිශීලක නාමය',
      'phone_no': 'දුරකථන අංකය',
      'email': 'විද්‍යුත් තැපෑල',
      'password': 'මුරපදය',
      'bus_no': 'බස් අංකය',
      'route_no': 'මාර්ග අංකය',
      'register': 'ලියාපදිංචි වන්න',
      'login': 'පුරනය වන්න',
      'forgot_password': 'මුරපදය අමතකද?',
      'registration_success': 'ලියාපදිංචිය සාර්ථකයි',
      'ok': 'හරි',
      'logout': 'ඉවත් වන්න',
      'about_us': 'අප ගැන',
      'version': 'අනුවාදය',
      'developed_by': 'නිර්මාණය කළේ',
      'released_date': 'නිකුත් කළ දිනය',
      'about_description':
          'බස් ගමනේ නිමක් නැති බලාපොරොත්තුව සහ අවිනිශ්චිතතාවයෙන් මහන්සි වී ද? අපිත් එහෙමයි.\n\nදෛනික ගමනාගමනකරුවන් සහ මෘදුකාංග ඉංජිනේරු සිසුන් ලෙස, අපි BusTrackLK නිර්මාණය කරමින් සිටිමු. අපගේ මෙහෙවර වන්නේ තත්‍ය කාලීන බස් ලුහුබැඳීම සහ කාලසටහන් පහසු ආසන වෙන්කිරීම දක්වා ගෙන ගොස්, අපගේ සම්පූර්ණ ප්‍රජාව සඳහා ගමන වඩාත් සරල හා පුරෝකථනය කළ හැකි බවට පත් කිරීමයි.',
    },
    'Tamil': {
      'app_name': 'பஸ்ட்ராக்LK',
      'driver_name': 'ஓட்டுநர் பெயர்',
      'start_location': 'தொடக்க இடம்',
      'end_location': 'இறுதி இடம்',
      'start_journey': 'பயணத்தைத் தொடங்கு',
      'profile': 'சுயவிவரம்',
      'about': 'பற்றி',
      'your_account_details': 'உங்கள் கணக்கு விவரங்கள்',
      'learn_more_about_us': 'எங்களைப் பற்றி மேலும் அறியுங்கள்',
      'copyright':
          '© 2025 பஸ்ட்ராக்LK பயன்பாடு. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
      'user_name': 'பயனர் பெயர்',
      'phone_no': 'தொலைபேசி எண்',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'bus_no': 'பேருந்து எண்',
      'route_no': 'பாதை எண்',
      'register': 'பதிவு செய்க',
      'login': 'உள்நுழைக',
      'forgot_password': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
      'registration_success': 'பதிவு வெற்றிகரமாக உள்ளது',
      'ok': 'சரி',
      'logout': 'வெளியேறு',
      'about_us': 'எங்களைப் பற்றி',
      'version': 'பதிப்பு',
      'developed_by': 'உருவாக்கியவர்',
      'released_date': 'வெளியிடப்பட்ட தேதி',
      'about_description':
          'பேருந்து பயணத்தின் முடிவற்ற காத்திருப்பு மற்றும் நிச்சயமற்ற தன்மையால் சோர்வாக உள்ளீர்களா? நாங்களும் அப்படித்தான்.\n\nதினசரி பயணிகள் மற்றும் மென்பொருள் பொறியியல் மாணவர்களாக, நாங்கள் BusTrackLK ஐ உருவாக்குகிறோம். எங்கள் நோக்கம் நேரடி பேருந்து கண்காணிப்பு மற்றும் அட்டவணைகளை எளிதான இருக்கை முன்பதிவு வரை கொண்டு வந்து, எங்கள் முழு சமூகத்திற்கும் பயணத்தை எளிமையாகவும் கணிக்கக்கூடியதாகவும் மாற்றுவதாகும்.',
    },
  };

  static String get(String key, String language) {
    return translations[language]?[key] ?? translations['English']?[key] ?? key;
  }
}
